App_Login/urls.py
from django.urls import path
from App_Login import views
app_name = 'App_Login'

urlpatterns = [
    path('signup/', views.Sign_up, name='Sign_up'),
    path('login/', views.Login_user, name='Login_user'),
    path('logout', views.Logout_user, name='Logout_user'),
    path('edit/', views.Edit_Profile, name='Edit_Profile'),
    path('profile/', views.user_profile, name='user_profile'),
    path('user_other/<username>/', views.User_other, name='user_other'),
    path('follow/<username>/', views.follow, name='follow'),
    path('unfollow/<username>/', views.Unfollow, name='unfollow'),

]

App_Post/urls.py
from django.urls import path
from App_Post import views
app_name = 'App_Post'

urlpatterns = [
    path('home/', views.Home, name='home'),
    path('post/', views.user_post, name='post'),
    path('like/<pk>/', views.Like_user, name='like'),
    path('unlike/<pk>/', views.Unlike_user, name='unlike'),

]

Social_Projec/urls.py
from django.contrib import admin
from django.urls import path, include
# Media display
from django.conf import settings
from django.contrib.staticfiles.urls import static, staticfiles_urlpatterns
from App_Post import views
urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('App_Login.urls')),
    path('post/', include('App_Post.urls')),
    path('', views.Home, name='home'),
]
urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

App_Login/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class UserProfile(models.Model):
    user = models.OneToOneField(User, related_name='user_profile', on_delete=models.CASCADE)
    profile_pic = models.ImageField(upload_to='profile_pics', blank=True)
    dob = models.DateField(null=True, blank=True)
    address = models.TextField(null=True, blank=True)
    facebook = models.URLField(null=True, blank=True)


class Follow(models.Model):
    follower = models.ForeignKey(User, related_name='follower', on_delete=models.CASCADE)
    following = models.ForeignKey(User, related_name='following', on_delete=models.CASCADE)
    created_date = models.DateTimeField(auto_now_add=True)

App_Login/forms.py
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm
from django.forms import ModelForm
from App_Login.models import UserProfile
from django import forms

class CreateNewUser(UserCreationForm):
    email = forms.EmailField(required=True, label='', widget=forms.TextInput(attrs={'placeholder': 'Put your email'}))
    username = forms.CharField(required=True, label='', widget=forms.TextInput(attrs={'placeholder': 'Write your username'}))
    password1 = forms.CharField(required=True, label='', widget=forms.PasswordInput(attrs={'placeholder': 'Password'}))
    password2 = forms.CharField(required=True, label='', widget=forms.PasswordInput(attrs={'placeholder': 'Password Confirmation'}))

    class Meta:
        model = User
        fields = ['username', 'email', 'password1', 'password2']

class EditProfile(forms.ModelForm):
    dob = forms.DateField(widget=forms.TextInput(attrs={'type': 'date'}))

    class Meta:
        model = UserProfile
        exclude = ['user']

App_Login/views.py
from django.shortcuts import render, HttpResponseRedirect
from django.http import HttpResponse
from django.urls import reverse, reverse_lazy

# Authentication
from django.contrib.auth.decorators import login_required
from django.contrib.auth import authenticate, login, logout

# Forms
from App_Login.forms import CreateNewUser, EditProfile
from django.contrib.auth.forms import AuthenticationForm

# Models
from django.contrib.auth.models import User
from App_Login.models import UserProfile, Follow

# Create your views here.
def Sign_up(request):
    form = CreateNewUser()
    registered = False
    if request.method == 'POST':
        form = CreateNewUser(data=request.POST)
        if form.is_valid():
            user = form.save()
            registered = True
            user_profile = UserProfile(user=user)
            user_profile.save()
            return HttpResponseRedirect(reverse('App_Login:Login_user'))
    diction = {'form': form}
    return render(request, 'App_Login/signup.html', context=diction)

def Login_user(request):
    form = AuthenticationForm()
    if request.method == 'POST':
        form = AuthenticationForm(data=request.POST)
        if form.is_valid():
            username = form.cleaned_data.get('username')
            password = form.cleaned_data.get('password')
            user = authenticate(username=username, password=password)
            if user is not None:
                login(request, user)
                return HttpResponseRedirect(reverse('App_Post:home'))
    diction = {'form': form}
    return render(request, 'App_Login/login.html', context=diction)

@login_required
def Logout_user(request):
    logout(request)
    return HttpResponseRedirect(reverse('App_Login:Login_user'))


@login_required
def Edit_Profile(request):
    current_user = UserProfile.objects.get(user=request.user)
    form = EditProfile(instance=current_user)
    if request.method == 'POST':
        form = EditProfile(request.POST, request.FILES, instance=current_user)
        if form.is_valid():
            form.save()
            form = EditProfile(instance=current_user)
            return HttpResponseRedirect(reverse('App_Login:user_profile'))
    diction = {'form': form}
    return render(request, 'App_Login/edit_profile.html', context=diction)
@login_required
def user_profile(request):
    return render(request, 'App_Login/user_profile.html', context={})

@login_required
def User_other(request, username):
    user_other = User.objects.get(username=username)
    already_followed = Follow.objects.filter(follower=request.user, following=user_other)
    if user_other == request.user:
        return HttpResponseRedirect(reverse('App_Login:user_profile'))
    diction = {'user_other': user_other, 'already_followed': already_followed}
    return render(request, 'App_Login/user_other.html', context=diction)

@login_required
def follow(request, username):
    following_user = User.objects.get(username=username)
    follower_user = request.user
    already_followed = Follow.objects.filter(follower=follower_user, following=following_user)
    if not already_followed:
        followed_user = Follow(follower=follower_user, following=following_user)
        followed_user.save()
    return HttpResponseRedirect(reverse('App_Login:user_other', kwargs={'username':username}))

def Unfollow(request, username):
    following_user = User.objects.get(username=username)
    follower_user = request.user
    already_followed = Follow.objects.filter(follower=follower_user, following=following_user)
    already_followed.delete()
    return HttpResponseRedirect(reverse('App_Login:user_other', kwargs={'username': username}))

templates/App_Login/edit_profile.html
{% extends 'navbar.html' %}
{% load crispy_forms_tags %}
{% block title_block %}
{% endblock %}
{% block body_block %}
    <form method="POST" enctype="multipart/form-data">
            {{ form|crispy }}
            {% csrf_token %}
            <br>
            <button type="submit" class="btn btn-sm btn-primary">Update</button>
    </form>

{% endblock %}

templates/App_Login/login.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block title_block %}
    User sign up
{% endblock %}
{% block css_block %}
    <style>
    .log_in{
        width: 550px ;
        padding:50px;
        border: 1px solid #ccc;
    }
    .signup{
        width: 300px;
        border: 1px solid #ccc;
        padding-top: 50px;
    }

    </style>
{% endblock%}

{% block body_block %}
    <center>
        <div class="log_in">
         <form method="POST">
            {{ form|crispy }}
            {% csrf_token %}
            <br>
            <button type="submit" class="btn btn-sm btn-primary">Login</button>
          </form>
        </div>
        <br>
        <div class="signup">
            <p>Do not Have a account please <a href="{% url 'App_Login:Sign_up' %}">SignUp</a></p>
        </div>
    </center>
{% endblock %}

templates/App_Login/signup.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block title_block %}
    User sign up
{% endblock %}
{% block css_block %}
    <style>
    .signup{
        width: 550px ;
        padding:50px;
        border: 1px solid #ccc;
    }
    .log_in{
        width: 300px;
        border: 1px solid #ccc;
        padding-top: 50px;
    }

    </style>
{% endblock%}

{% block body_block %}
    <center>
        <div class="signup">
         <form method="POST">
            {{ form|crispy }}
            {% csrf_token %}
            <br>
            <button type="submit" class="btn btn-sm btn-primary">Sign Up</button>
          </form>
        </div>
        <br>
        <div class="log_in">
            <p>Have a account please <a href="{% url 'App_Login:Login_user' %}">Login</a></p>
        </div>
    </center>
{% endblock %}

templates/App_Login/user_other.html
{% extends 'navbar.html' %}
{% load crispy_forms_tags %}
{% load static %}
{% block title_block %} {{user_other.user_profile.fullname}} (@{{ user_other.username }}) {%endblock%}
{% block css_block %}
<style>
  .crop {
    width: 200px;
    height: 200px;
    overflow: hidden;
  }

  .crop img {
    width: 200px;
    height: 200px;
    margin: -75px 0 0 -100px;
  }
</style>
{% endblock%}
{% block body_block %}
<div class="row">
  <div class="col-sm-4">
      {% if user_other.user_profile.profile_pic %}
        <img src="/media/{{ user_other.user_profile.profile_pic }}" width="250px" height="250px" class="rounded-circle">
      {% else %}
         <img src="/media/arif.png" width="250px" height="250px" class="rounded-circle">
      {% endif %}
  </div>

  <div class="col-sm-8">
      <h1>{{ user_other.username }}&nbsp;
          {% if not already_followed %}
              <a href="{% url 'App_Login:follow' username=user_other.username %}" class="btn btn-sm btn-primary">Follow</a></h1>
          {% else %}
                <a href="{% url 'App_Login:follow' username=user_other.username %}" class="btn btn-sm btn-primary">Unfollow</a>
          {% endif %}
     </h1>

    <br>
    <h4>{{ user_other.post_author.count }} posts &nbsp; &nbsp; {{ user_other.following.count }} followers &nbsp; &nbsp; {{ user_other.follower.count }} following</h4>
    <br>
    <h3>{{ user_other.user_profile.fullname }}</h3>
  </div>
</div>
<hr>
<br>
<br>
    <div class="row">
    {% for post in user_other.post_author.all %}
    <div class="col-sm-3">
        <img src="/media/{{ post.image }}" alt="" width="400px">
    </div>
    {% endfor %}
    </div>
{% endblock %}

templates/App_Login/user_profile.html
{% extends 'navbar.html' %}
{% load crispy_forms_tags %}
{% load static %}
{% block title_block %} {{user.user_profile.fullname}} (@{{ user.username }}) {%endblock%}
{% block css_block %}
<style>
  .crop {
    width: 200px;
    height: 200px;
    overflow: hidden;
  }

  .crop img {
    width: 200px;
    height: 200px;
    margin: -75px 0 0 -100px;
  }
</style>
{% endblock%}
{% block body_block %}
<div class="row">
  <div class="col-sm-4">
      {% if user.user_profile.profile_pic %}
        <img src="/media/{{ user.user_profile.profile_pic }}" width="250px" height="250px" class="rounded-circle">
      {% else %}
         <img src="/media/arif.png" width="250px" height="250px" class="rounded-circle">
      {% endif %}
  </div>

  <div class="col-sm-8">

      <h1>{{ user.username }} &nbsp;<a href="{% url 'App_Login:Edit_Profile' %}" class="btn btn-sm btn-light">Edit_Profile</a>
     </h1>&nbsp;

    <br>
    <h4>{{ user.post_author.count }} posts &nbsp; &nbsp; {{ user.following.count }} followers &nbsp; &nbsp; {{ user.follower.count }} following</h4>
    <br>
    <h3>{{ user.user_profile.fullname }}</h3>
  </div>
</div>
<hr>
<br>
<br>
    <div class="row">
    {% for post in user.post_author.all %}
    <div class="col-sm-3">
        <img src="/media/{{ post.image }}" alt="" width="400px">
    </div>
    {% endfor %}
    </div>

{% endblock %}