App_Login/urls.py
from django.urls import path
from App_Login import views
app_name = 'App_Login'

urlpatterns = [
    path('signup/', views.Sign_up, name='Sign_up'),
    path('login/', views.Login_user, name='Login_user'),
    path('logout', views.Logout_user, name='Logout_user'),
    path('edit/', views.Edit_Profile, name='Edit_Profile'),
    path('profile/', views.user_profile, name='user_profile'),
    path('user_other/<username>/', views.User_other, name='user_other'),
    path('follow/<username>/', views.follow, name='follow'),
    path('unfollow/<username>/', views.Unfollow, name='unfollow'),

]

App_Post/urls.py
from django.urls import path
from App_Post import views
app_name = 'App_Post'

urlpatterns = [
    path('home/', views.Home, name='home'),
    path('post/', views.user_post, name='post'),
    path('like/<pk>/', views.Like_user, name='like'),
    path('unlike/<pk>/', views.Unlike_user, name='unlike'),

]

Social_Projec/urls.py
from django.contrib import admin
from django.urls import path, include
# Media display
from django.conf import settings
from django.contrib.staticfiles.urls import static, staticfiles_urlpatterns
from App_Post import views
urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('App_Login.urls')),
    path('post/', include('App_Post.urls')),
    path('', views.Home, name='home'),
]
urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <title>{% block title_block %}  {% endblock %}</title>
   {% block css_block %}

   {% endblock %}
</head>
<body>
<div class="container" style="padding-top:20px">
    {% block body_block %}

     {%  endblock %}
</div>

</body>
</html>

templates/navbar.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <title>{% block title_block %} Blogs {% endblock %}</title>
</head>
<body>
<nav class="navbar navbar-expand-sm navbar-dark bg-dark">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <a class="nav-link" href="{% url 'App_Post:home' %}">Home</a>
      </li>

     <li class="nav-item active">
        <a class="nav-link" href="{% url 'App_Post:post' %}">Create Post</a>
      </li>
       &nbsp; &nbsp;&nbsp;
         <form class="form-inline" method="GET">
              <input class="form-control mr-sm-2" name="search" type="search" placeholder="Search" aria-label="Search">
              <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
          </form>
        <li class="nav-item active">
            <a class="nav-link" href="{% url 'App_Login:Logout_user' %}">Logout</a>
        </li>
         <li class="nav-item active">
             {% if user.user_profile.profile_pic %}
                    <a class="nav-link" href="{% url 'App_Login:user_profile' %}"><img src="/media/{{ user.user_profile.profile_pic }}" width="40px" height="40px" class="rounded-circle"></a>
             {% else %}
               <a class="nav-link" href="{% url 'App_Login:user_profile' %}"><img src="/media/arif.png" width="40px" height="40px" class="rounded-circle"></a>
             {% endif %}
      </li>

    </ul>


</nav>
<div class="container" style="padding-top:20px"></div>
{% block body_block %}

{%  endblock %}

</body>
</html>