App_Login/urls.py
from django.urls import path
from App_Login import views
app_name = 'App_Login'

urlpatterns = [
    path('signup/', views.Sign_up, name='Sign_up'),
    path('login/', views.Login_user, name='Login_user'),
    path('logout', views.Logout_user, name='Logout_user'),
    path('edit/', views.Edit_Profile, name='Edit_Profile'),
    path('profile/', views.user_profile, name='user_profile'),
    path('user_other/<username>/', views.User_other, name='user_other'),
    path('follow/<username>/', views.follow, name='follow'),
    path('unfollow/<username>/', views.Unfollow, name='unfollow'),

]

App_Post/urls.py
from django.urls import path
from App_Post import views
app_name = 'App_Post'

urlpatterns = [
    path('home/', views.Home, name='home'),
    path('post/', views.user_post, name='post'),
    path('like/<pk>/', views.Like_user, name='like'),
    path('unlike/<pk>/', views.Unlike_user, name='unlike'),

]

Social_Projec/urls.py
from django.contrib import admin
from django.urls import path, include
# Media display
from django.conf import settings
from django.contrib.staticfiles.urls import static, staticfiles_urlpatterns
from App_Post import views
urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('App_Login.urls')),
    path('post/', include('App_Post.urls')),
    path('', views.Home, name='home'),
]
urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

App_Post/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class Post(models.Model):
    author = models.ForeignKey(User, related_name='post_author', on_delete=models.CASCADE)
    image = models.ImageField(upload_to='post_pic', blank=True)
    caption = models.TextField(max_length=50, blank=True)
    date = models.DateTimeField(auto_now_add=True)
    update_date = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ['-date']


class Like(models.Model):
    post = models.ForeignKey(Post, related_name='like_post', on_delete=models.CASCADE)
    user = models.ForeignKey(User, related_name='liker_post', on_delete=models.CASCADE)
    date = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return '{}:{}'.format(self.user, self.post)

App_Post/forms.py
from django.forms import ModelForm
from django import forms
from App_Post.models import Post

class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ['image', 'caption', ]

App_Post/views.py
from django.shortcuts import render, HttpResponseRedirect
from django.urls import reverse
# Authentication
from django.contrib.auth.decorators import login_required
# FORMS
from App_Post.forms import PostForm
# Models
from App_Post.models import Post
from django.contrib.auth.models import User
from App_Login.models import Follow
from App_Post.models import Like
# Create your views here.
@login_required
def Home(request):
    # This part of all Post Display process
    following_list = Follow.objects.filter(follower=request.user)
    Posts = Post.objects.filter(author__in=following_list.values_list('following'))
    # End of  all post  Display process
    # This part of all post like process
    liked_post = Like.objects.filter(user=request.user)
    liked_post_list = liked_post.values_list('post', flat=True)
    # End of all post like process
    # This part of search button process
    if request.method == 'GET':
        search = request.GET.get('search', '')
        result = User.objects.filter(username__contains=search)
    # End of search button process
    diction = {'search': search, 'result': result, 'Posts': Posts, 'like_post_list': liked_post_list}
    return render(request, 'App_Post/home.html', context=diction)

@login_required
def user_post(request):
    form = PostForm()
    if request.method == 'POST':
        form = PostForm(request.POST, request.FILES)
        if form.is_valid():
            post = form.save(commit=False)
            post. author = request.user
            post.save()
            return HttpResponseRedirect(reverse('App_Login:user_profile'))
    diction = {'form': form}
    return render(request, 'App_Post/post_form.html', context=diction)

@login_required
def Like_user(request, pk):
    post = Post.objects.get(pk=pk)
    user = request.user
    already_liked = Like.objects.filter(post=post, user=user)
    if not already_liked:
        liked = Like(post=post, user=user)
        liked.save()
    return HttpResponseRedirect(reverse('App_Post:home'))

@login_required
def Unlike_user(request, pk):
    post = Post.objects.get(pk=pk)
    user = request.user
    already_liked = Like.objects.filter(post=post, user=user)
    already_liked.delete()
    return HttpResponseRedirect(reverse('App_Post:home'))

templates/App_Post/home.html
{% extends 'navbar.html' %}
{% block title_block %}
{% endblock %}
{% block body_block %}
      <!-- this part is search for search user display -->
    {% if search %}
        {% for search_user in result %}
            <div class="row">
            <div class="col-sm-2">
                {% if search_user.user_profile.profile_pic %}
                <img src="/media/{{ search_user.user_profile.profile_pic }}" width="75px" height="75px" class="rounded-circle">
                {% else %}
                 <img src="/media/arif.png" width="75px" height="75px" class="rounded-circle">
                {% endif %}
            </div>
            <div class="col-sm-10">
               <a href="{% url 'App_Login:user_other' username=search_user.username %}">{{ search_user.username }}</a>
                <br>
                {{ search_user.user_profile.fullname }}
            </div>
            </div>
        {% endfor %}
        <!-- this part is home page for post display -->
      {% else %}
        <div class="row">
        <div class="col-sm-8">
         {% for post in Posts %}
             <div style="border: 1px solid #ccc">
                 <div style="padding: 10px">
                      {% if post.author.user_profile.profile_pic %}
                         <img src="/media/{{ post.author.user_profile.profile_pic }}" width="75px" height="75px" class="rounded-circle">
                     {% else %}
                         <img src="/media/arif.png" width="75px" height="75px" class="rounded-circle">
                     {% endif %}
                   <a href="{% url 'App_Login:user_other' username=post.author %}">{{ post.author }}</a>
                 </div>
              <img src="/media/{{ post.image }}" width="100%">
               <div style="padding:20px">
                   {% if post.pk in like_post_list %}
                       <a href="{% url 'App_Post:unlike' pk=post.pk %}"> <i class="fa fa-heart-o" style="font-size:36px"></i></a>
                   {% else %}
                      <a href="{% url 'App_Post:like' pk=post.pk %}"> <i class="fa fa-heart" style="font-size:36px"></i></a>
                   {% endif %}
               </div>
             </div>
             <br>
             <br>
             <br>
          {% endfor %}
        </div>
        <div class="col-sm-4">
         <!-- this part is home page for login user profile display -->
            <div class="row">
                <div class="col-sm-4">
                     {% if user.user_profile.profile_pic %}
                <img src="/media/{{ user.user_profile.profile_pic }}" width="75px" height="75px" class="rounded-circle">
                {% else %}
                 <img src="/media/arif.png" width="75px" height="75px" class="rounded-circle">
                {% endif %}
                </div>
                <div class="col-sm-8">
                   <a href="{% url 'App_Login:user_profile' %}">{{ user.username }}</a>
                </div>
            </div>
        </div>
     {% endif %}
{% endblock %}

templates/App_Post/post_form.html
{% extends 'navbar.html' %}
{% load crispy_forms_tags %}
{% block title_block %}
{% endblock %}
{% block body_block %}
    <form method="POST" enctype="multipart/form-data">
            {{ form|crispy }}
            {% csrf_token %}
            <br>
            <button type="submit" class="btn btn-sm btn-primary">Post</button>
    </form>
{% endblock %}